UKHomeOffice/ref-data-api

- Dockerfile
- README.md
Builds the API app into a Docker image, running Node Alpine.
> Builds a Docker image to run the app in

- .drone.yml
- kube/deployment.yml
- kube/ingress.yml
- kube/network-policy.yml
- kube/service.yml
Automates:
- Docker build
- Push to Quay.io
- Deploy to kube dev cluster (master branch only)
> Add drone pipeline and deploy to kube

- test/helpers/index.test.js
- test/routes/entities.test.js
- test/routes/items.test.js
- test/services/entities.test.js
- test/services/items.test.js
This PR adds functionality to disable logging when executing tests.
> Disable logging when executing tests

- .drone.yml
- README.md
- config/core.js
- kube/deployment.yml
Changes the reference to the DB connection
> Changed the DB connection secret

- config/core.js
- db/entities.js
- db/items.js
- package-lock.json
- package.json
- routes/entities.js
- routes/index.js
- test/routes/entities.test.js
To test
* download Camunda and Camunda modeler
* start Camunda (and Camunda modeler if you need to add/create a process otherwise no need)
* create a process and name it `reference-data-approval`
* Using Postman POST to the following url `http://localhost:5000/v1/entities/country` set Headers to `Content-Type` - `application/json` and the body `raw` to:
```
{
"iso31661alpha2": "FJ",
iso31661alpha3": "FJI",
"name": "Fiji",
"continent": "OC",
"dial": "679",
"iso31661numeric": "242"
}
```
* hit 'Send'
> New entity item camunda

- config/core.js
- package-lock.json
- package.json
- routes/entities.js
- routes/index.js
- routes/items.js
- test/routes/entities.test.js
- test/routes/items.test.js
This PR allows the submition of field value update requests to Camunda.
> Patch item field value

- routes/entities.js
This PR adds functionality that allows users to query for the entity schema or the entity schema and entity data (default)
If you just want the entity schema use `?schemaOnly=true` at the end of the endpoint:
`http://localhost:5000/v1/entities/:name?schemaOnly=true`
> Process query params

- package-lock.json
- package.json
- routes/entities.js
- routes/index.js
- routes/items.js
- test/routes/entities.test.js
- test/routes/index.test.js
- test/routes/items.test.js
Adds functionality to:
* decode a jwt token;
* check if the token expiration date is in the future;
* extract token data (such as the user role)
> Token decoding

- .gitignore
- kube/deployment.yml
Prevents the nginx proxy from appending the UUID to the URL
> Stop nginx appending uuid to url

- db/entities.js
- routes/entities.js
* Restrict the return of empty schemas
* Ensure when querying the API for a non-existing entity an error message is return
> Restrict the return of empty schemas

- routes/entities.js
Signed-off-by: Pedro Miguel <pedro.miguel@live.co.uk>
> Fix wrong object structure being returned

- .drone.yml
Added test step to automate testing drone CI pipeline
> Add test step

- .drone.yml
Only trigger the prod deployment for prod deployments :)
> Prevent testing and building on deployments

- .drone.yml
> Add lint checks

- routes/entities.js
- routes/items.js
Remove nested description object from:
* entities  -  /entities
* entity  -  /entities/country
* item  -  /entities/country/items/3
> Update schema structure

- Dockerfile
- config/core.js
- healthcheck.js
- kube/deployment.yml
- package-lock.json
- package.json
- routes/health.js
- routes/index.js
To test
* Deploy using docker (please refer to the README);
* Open a new terminal tab and execute `docker ps` over and over until you see the status `healthy` should take around 10secs;
* To test `unhealthy` status, change the status returned from the health route from 200 to 400 and repeat the steps above.
* Console log is required to store the messages from triggered by the Docker `HEALTHCHECK` command, these messages can be seen in the when inspecting the container.
> Add service health check

- .drone.yml
> Updated .drone.yml for Staging

- app/db/utils.js
- test/db/utils.test.js
Add additional filtering options with tests
gt, gte, lt, lte
> Cb 346 filtering

- app/routes/entities.js
- app/routes/items.js
- app/routes/v1/index.js
- test/routes/entities.test.js
- test/routes/items.test.js
Ensures the API responses are according to SWAGGER documentation
> Minor updates to reflect swagger

- .drone.yml
- README.md
- env.yaml
- kube/deployment.yml
- kube/secret.yml
- Use named kubenamespace variable
- Synch secrets on deployment to secrets
- Updated readme with env variable list and values
- Use protocol constant variables
> CB-717 Repository improvements

- app/routes/index.js
This PR logs the token role for each user in each request
> Log token role

- app/db/index.js
- app/routes/entities.js
- app/routes/items.js
> CB-1097 Reference data permission denied errors

- .drone.yml
Using the environment and secrets stanzas does not seem to work
> CB-1097 Explicitly export db role environment variables

- app/db/models/border-crossing-mode.js
- test/db/models/border-crossing-mode.test.js
Schema: https://github.com/UKHomeOffice/RefData/blob/master/schemas/reference/V31__bordercrossingmode.sql
> [COP-238] Adds the BorderCrossingMode model and unit tests

- app/db/models/carrier-list.js
- app/db/models/crew-role.js
- app/db/models/document-type.js
- app/db/models/dog-role.js
- test/db/models/carrier-list.test.js
- test/db/models/crew-role.test.js
- test/db/models/document-type.test.js
- test/db/models/dog-role.test.js
Table models for :
V17__carrierlist
V19__crewrole
V21__documenttype
V22__dogrole
> New table models

- kube/deployment.yml
Increase ref-data-api cpu and memory limits same as Postgrest permanently
\* Required
Yes
Yes
Yes
Yes
> COP2349-cpu

- .drone.yml
- env.yaml
> COP-2549 Integrating SNOW to ref-data-api drone pipeline

- app/config/core.js
- docker-compose.yml
- docs/environment-variables.md
- docs/setup.md
Fix an outdated Docker configuration to enable local development on the project.
\* Required
> COP-3216: Update the Docker configuration to enable running the API locally

- Dockerfile
Upgrade node version from 10 to 12 for better performance and more features.
\* Required
> Upgrade Node to version 12

- app/routes/middlewares/auth.js
- test/routes/index.test.js
- test/routes/middlewares/auth.test.js
Improve error messages when authorizing user.
\* Required
> Improve error messages during authorization

- kube/deployment.yml
> COP4266-Fixing Ref-api-url

- app/routes/middlewares/auth.js
> Add temporary logging to debug incorrect hawk auth

- app/routes/middlewares/auth.js
> Fix HAWK authorization when behind a proxy

- app/routes/middlewares/auth.js
Remove temporary logging introduced in #186 to debug Hawk authorisation.
\* Required
> Remove temporary logging introduced in #186

- .drone.yml
- env.yaml
> COP-5504 drone pipeline update

- .drone.yml
> cop-6733 updated env.yaml for sit
